export const NAME = {
  //controllers
  DOCUMENT_VIEW_CONTROLLER: "DOCUMENT_VIEW_CONTROLLER",
  DOCUMENT_MODEL_CONTROLLER: "DOCUMENT_MODEL_CONTROLLER",
  BUILDER_VIEW_CONTROLLER: "BUILDER_VIEW_CONTROLLER",
  BUILDER_MODEL_CONTROLLER: "BUILDER_MODEL_CONTROLLER",
  PAGES_VIEW_CONTROLLER: "PAGES_VIEW_CONTROLLER",
  PAGES_VIEW_TAB_CONTROLLER: "PAGES_VIEW_TAB_CONTROLLER",
  PAGE_TAB_LIST_ITEM_VIEW_CONTROLLER: "PAGE_TAB_LIST_ITEM_VIEW_CONTROLLER",

  //channels
  BUILDER_CHANNEL: "BUILDER_CHANNEL",

  //events
  NEW_PAGE_WAS_ADDED: "NEW_PAGE_WAS_ADDED",
};
